# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/FalconsFactionMonitor/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "Australia/Brisbane"
    open-pull-requests-limit: 1
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Xaml.Behaviors.Wpf"
        versions: ["1.1.*"]